"""empty message

Revision ID: 05ad4ad0e334
Revises: 9051c8068a23
Create Date: 2022-08-02 21:39:20.678592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ad4ad0e334'
down_revision = '9051c8068a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'developers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'developers', type_='foreignkey')
    op.drop_column('developers', 'user_id')
    # ### end Alembic commands ###
