"""empty message

Revision ID: 587f1ffaca5b
Revises: 60c0f334133a
Create Date: 2022-08-03 19:42:57.578570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '587f1ffaca5b'
down_revision = '60c0f334133a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
