"""empty message

Revision ID: bc3a1b865385
Revises: 587f1ffaca5b
Create Date: 2022-08-03 20:43:02.426999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3a1b865385'
down_revision = '587f1ffaca5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'initials',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('states', 'initials',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
