"""empty message

Revision ID: ebbcf23889ff
Revises: 05ad4ad0e334
Create Date: 2022-08-02 21:55:26.889640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbcf23889ff'
down_revision = '05ad4ad0e334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_technologies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('developer_id', sa.Integer(), nullable=False),
    sa.Column('is_main_tech', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_technologies')
    # ### end Alembic commands ###
